/*
 * Generated by VueOneMapper. The original code-behind only issued controller
 * commands, which a monitoring HMI must not do.
 */

using System;
using NxtControl.GuiFramework;

namespace HMI.Main.Symbols.Seven_State_Actuator_Centre_Home_CAT
{
	public partial class sDefault : NxtControl.GuiFramework.HMISymbol
	{
		public sDefault()
		{
			InitializeComponent();
		}
	}
}
