/*
 * Generated by VueOneMapper from this CAT's own sDefault plus the reference Setup button pattern.
 * The jog controls are bound to the declared output tags; NxtControl writes them and raises the
 * carrying cmd_event, so there is no command code here to get out of step with the contract.
 *
 * The mode gate below is the reference's own contract, taken verbatim from
 * Five_State_Actuator_CAT_sSetup: a jog control is disabled until the controller CONFIRMS Setup
 * mode, and re-disabled the moment it leaves. Without it a three-position jog would be pressable
 * while the plant was running Automatic - which is exactly what this faceplate did before, and the
 * one place where it departed from the two-position faceplate it was derived from.
 */

using System;
using NxtControl.GuiFramework;

namespace HMI.Main.Symbols.Seven_State_Actuator_Centre_Home_CAT
{
	public partial class sSetup : NxtControl.GuiFramework.HMISymbol
	{
		public sSetup()
		{
			InitializeComponent();
			mode_event_Fired += ModeChanged;
			// Direct commands disabled until Setup mode is confirmed
			toWork1.Enabled = false;
			toHome.Enabled = false;
			toWork2.Enabled = false;
		}

		void ModeChanged(object sender, mode_eventEventArgs e)
		{
			bool setupMode = e.ModeCMD.Value == 3;

			// Enable direct actuator interaction only in Setup mode
			toWork1.Enabled = setupMode;
			toHome.Enabled = setupMode;
			toWork2.Enabled = setupMode;
		}
	}
}
