//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HwConfiguration
{
    using System;
    
    
    public partial class TM3BC_Ethe_R1C9LFqq0OfJh : NxtControl.Automation.DeviceConfigurator.HWCAT
    {
        
        /// 
        public TM3BC_Ethe_R1C9LFqq0OfJh.ComplexPropertyConnectinfo connectinfo = new TM3BC_Ethe_R1C9LFqq0OfJh.ComplexPropertyConnectinfo();
        
        /// 
        public TM3BC_Ethe_R1C9LFqq0OfJh.ComplexPropertyInput0 input0 = new TM3BC_Ethe_R1C9LFqq0OfJh.ComplexPropertyInput0();
        
        /// 
        public TM3BC_Ethe_R1C9LFqq0OfJh.ComplexPropertyOutput0 output0 = new TM3BC_Ethe_R1C9LFqq0OfJh.ComplexPropertyOutput0();
        
        /// Standard.IoEtherNetIP.guid.Description
        public string guid
        {
            get
            {
                return GetNamedProperty<string>("guid");
            }
            set
            {
                SetNamedProperty<string>("guid", value);
            }
        }
        
        public class ComplexPropertyConnectinfo : NxtControl.Automation.DeviceConfigurator.HWCATProperties
        {
            
            /// Standard.IoEtherNetIP.connectinfo.devicenumber.Description
            public ushort devicenumber
            {
                get
                {
                    return GetNamedProperty<ushort>("connectinfo.devicenumber");
                }
                set
                {
                    SetNamedProperty<ushort>("connectinfo.devicenumber", value);
                }
            }
            
            /// Standard.IoEtherNetIP.connectinfo.ipaddress.Description.Slave
            public string ipaddress
            {
                get
                {
                    return GetNamedProperty<string>("connectinfo.ipaddress");
                }
                set
                {
                    SetNamedProperty<string>("connectinfo.ipaddress", value);
                }
            }
            
            /// RIO embeded
            public bool RIO
            {
                get
                {
                    return GetNamedProperty<bool>("connectinfo.RIO");
                }
                set
                {
                    SetNamedProperty<bool>("connectinfo.RIO", value);
                }
            }
        }
        
        public class ComplexPropertyInput0 : NxtControl.Automation.DeviceConfigurator.HWCATProperties
        {
            
            /// Standard.IoEtherNetIP.objectid.Description.Inputs
            public uint objectid
            {
                get
                {
                    return GetNamedProperty<uint>("input0.objectid");
                }
                set
                {
                    SetNamedProperty<uint>("input0.objectid", value);
                }
            }
            
            /// Standard.IoEtherNetIP.memoryRequested.Description
            public uint MemoryRequested
            {
                get
                {
                    return GetNamedProperty<uint>("input0.MemoryRequested");
                }
                set
                {
                    SetNamedProperty<uint>("input0.MemoryRequested", value);
                }
            }
            
            /// Standard.IoEtherNetIP.ioevent.Description
            public string ioevent
            {
                get
                {
                    return GetNamedProperty<string>("input0.ioevent");
                }
                set
                {
                    SetNamedProperty<string>("input0.ioevent", value);
                }
            }
        }
        
        public class ComplexPropertyOutput0 : NxtControl.Automation.DeviceConfigurator.HWCATProperties
        {
            
            /// Standard.IoEtherNetIP.objectid.Description.Outputs
            public uint objectid
            {
                get
                {
                    return GetNamedProperty<uint>("output0.objectid");
                }
                set
                {
                    SetNamedProperty<uint>("output0.objectid", value);
                }
            }
            
            /// Standard.IoEtherNetIP.memoryRequested.Description
            public uint MemoryRequested
            {
                get
                {
                    return GetNamedProperty<uint>("output0.MemoryRequested");
                }
                set
                {
                    SetNamedProperty<uint>("output0.MemoryRequested", value);
                }
            }
            
            /// Standard.IoEtherNetIP.ioevent.Description
            public string ioevent
            {
                get
                {
                    return GetNamedProperty<string>("output0.ioevent");
                }
                set
                {
                    SetNamedProperty<string>("output0.ioevent", value);
                }
            }
        }
    }
}
