using CodeGen.Models;
using System.Collections.Generic;
using System.Linq;

namespace CodeGen.Mapping
{
    /// <summary>
    /// Produces the complete VueOne → IEC 61499 mapping-rule rows as defined in
    /// VueOne_IEC61499_Mapping.xlsx.
    ///
    /// Row order mirrors the spreadsheet:
    ///   System rows first (SystemID, System/Name, Version, Type)
    ///   Then per-component rows in the order they appear in the xlsx table.
    ///
    /// All rows have Validated = true.
    /// DISCARDED rows are still validated — they represent deliberate drop decisions.
    /// </summary>
    public static class MappingRuleEngine
    {
        // ── colour hints (used by MainForm to pick row BackColor) ─────────────
        // Type → BackColor string is resolved in the UI layer; engine is colour-agnostic.

        // ─────────────────────────────────────────────────────────────────────
        // PUBLIC API
        // ─────────────────────────────────────────────────────────────────────

        /// <summary>
        /// System-level rows — appear once at the top regardless of component count.
        /// </summary>
        public static List<MappingRule> GetSystemRules(string systemId, string systemName)
        {
            return new List<MappingRule>
            {
                R("<SystemID>",
                  "GUID (FBType)",
                  MappingType.ASSUMED,
                  "Generate new UUID — don't reuse VueOne ID",
                  $"Every FB needs unique GUID. Source value: {Trunc(systemId, 30)}"),

                R("<System/Name>",
                  "FBType Name (in system file)",
                  MappingType.TRANSLATED,
                  $"Copy to system FB Name → \"{systemName}\"",
                  "Phase 2: System file generation"),

                R("<Version>",
                  "N/A",
                  MappingType.DISCARDED,
                  "Not used in IEC 61499",
                  "VueOne metadata only"),

                R("<Type> (System attribute)",
                  "N/A",
                  MappingType.DISCARDED,
                  "System type classification not mapped",
                  "VueOne classification"),
            };
        }

        /// <summary>
        /// Component-level rows — one block per VueOneComponent, in xlsx table order.
        /// </summary>
        public static List<MappingRule> GetComponentRules(VueOneComponent c)
        {
            var fbType = ResolveFbType(c);
            var param = ResolveParam(c);
            var rules = new List<MappingRule>();

            // ── Component identity ────────────────────────────────────────────

            rules.Add(R($"<Component/ComponentID>",
                        "N/A",
                        MappingType.DISCARDED,
                        "IEC 61499 uses GUID instead",
                        $"Dropped: {Trunc(c.ComponentID, 30)}"));

            rules.Add(R($"<Component/Name> = \"{c.Name}\"",
                        $"FB Name=\"{c.Name}\" (system file FB element)",
                        MappingType.TRANSLATED,
                        $"Component name → FB instance name",
                        "Phase 2: Instance creation — primary translation"));

            rules.Add(R("<Component/VcID>",
                        "N/A",
                        MappingType.DISCARDED,
                        "Visual Components metadata — not used in control logic",
                        "e.g. 'Pusher'"));

            rules.Add(R("<Component/Description>",
                        "Comment (optional)",
                        MappingType.ASSUMED,
                        "Could map to Comment attribute — not yet implemented",
                        "Low priority"));

            rules.Add(R("<Component/Library_ID>",
                        "N/A",
                        MappingType.DISCARDED,
                        "VueOne library reference — no IEC 61499 equivalent",
                        "Not applicable"));

            rules.Add(R($"<Component/Type> = \"{c.Type}\"",
                        $"Type=\"{fbType}\"",
                        MappingType.TRANSLATED,
                        $"{c.Type} → {fbType}",
                        "Determines which CAT template is selected"));

            // ── GUID (generated) ──────────────────────────────────────────────

            rules.Add(R("(none — not in Control.xml)",
                        $"GUID for FB instance \"{c.Name}\"",
                        MappingType.ASSUMED,
                        "UUID generated by mapper at injection time",
                        "Every FB instance requires a unique GUID"));

            // ── FB Type (hardcoded per template) ──────────────────────────────

            rules.Add(R("(none)",
                        $"Type=\"{fbType}\"",
                        MappingType.HARDCODED,
                        $"Every {c.States.Count}-state {c.Type} always maps to {fbType}",
                        "Template type is fixed — not derived from XML"));

            // ── CAT parameter injection ───────────────────────────────────────

            rules.Add(R($"<Component/Name> = \"{c.Name}\"",
                        param.iecElement,
                        MappingType.TRANSLATED,
                        param.rule,
                        "CAT instance parameter injection"));

            // ── State / StateID ───────────────────────────────────────────────

            rules.Add(R($"<State/StateID> ({c.States.Count} states)",
                        "N/A",
                        MappingType.DISCARDED,
                        "IEC 61499 ECC uses State Name only — ID is dropped",
                        "VueOne-specific identifier"));

            // ── Per-state rows ────────────────────────────────────────────────

            foreach (var s in c.States.OrderBy(x => x.StateNumber))
            {
                rules.Add(R($"<State/Name> = \"{s.Name}\" (State {s.StateNumber})",
                            $"ECState Name=\"{s.Name}\"  (in Actuator.fbt ECC)",
                            MappingType.ENCODED,
                            "State name maps to ECC state name in template FB",
                            s.InitialState ? "★ Initial state" : ""));

                rules.Add(R($"<State/State_Number> = {s.StateNumber}",
                            "state_val (InputVar)",
                            MappingType.TRANSLATED,
                            $"Direct INT mapping: state_val := {s.StateNumber}",
                            "Used for state identification in data connections"));

                if (s.InitialState)
                    rules.Add(R($"<State/Initial_State> = True  → \"{s.Name}\"",
                                "ECTransition Source=\"START\"",
                                MappingType.ENCODED,
                                $"True → Source='START' Destination='{s.Name}'",
                                "Phase 3: Initialization"));
            }

            // ── Simulation-only state attributes ─────────────────────────────

            rules.Add(R("<State/Time>",
                        "N/A (watchdog candidate)",
                        MappingType.ASSUMED,
                        "Could map to timeout logic — future phase",
                        "Not yet implemented"));

            foreach (var d in new[]
            {
                ("<State/Speed>",       "PLC controls physical speed — not part of FB logic layer"),
                ("<State/Position>",    "PLC setpoint, not FB logic — future: System Configuration"),
                ("<State/Operator>",    "VueOne simulation feature — not applicable to IEC 61499"),
                ("<State/Counter>",     "VueOne counting feature — not applicable"),
                ("<State/EndCounter>",  "VueOne simulation feature — not applicable"),
                ("<State/StateColour>", "Visual representation only — not used in control logic"),
                ("<State/RobotAxes>",   "Robot-specific metadata — not applicable to general actuators"),
            })
                rules.Add(R(d.Item1, "N/A", MappingType.DISCARDED, d.Item2, ""));

            rules.Add(R("<State/StaticState>",
                        "Motion state indicator",
                        MappingType.ENCODED,
                        "False = motion/transient state, True = position hold (static)",
                        "Affects interlock logic interpretation"));

            // ── Transition rows ───────────────────────────────────────────────

            foreach (var d in new[]
            {
                ("<Transition/TransitionID>", "VueOne-specific ID — IEC 61499 does not use transition IDs"),
                ("<Transition/Type>",         "VueOne transition classification — not used in IEC 61499"),
                ("<Transition/Priority>",     "VueOne scheduling feature — IEC 61499 uses event priority"),
            })
                rules.Add(R(d.Item1, "N/A", MappingType.DISCARDED, d.Item2, ""));

            rules.Add(R("<Transition/Origin_State>",
                        "ECTransition Source",
                        MappingType.ENCODED,
                        "StateID looked up → Name (Phase 3: Transition logic)",
                        "e.g. S-7d375f41... → Source='ReturnedHome'"));

            rules.Add(R("<Transition/Destination_State>",
                        "ECTransition Destination",
                        MappingType.ENCODED,
                        "StateID looked up → Name (Phase 3: Transition logic)",
                        "e.g. S-5376706a... → Destination='Advancing'"));

            // ── Sequence / Interlock conditions ───────────────────────────────

            rules.Add(R("<Sequence_Condition>",
                        "EventConnection Source/Destination (system file)",
                        MappingType.ENCODED,
                        "Parse condition tree → event wiring in syslay/sysres",
                        "Phase 3–4: Event connections"));

            rules.Add(R("<ConditionGroup>",
                        "AND logic in ECTransition guard",
                        MappingType.ENCODED,
                        "Multiple conditions ANDed (Group_1 → cond1 AND cond2)",
                        "Phase 4: Complex conditions"));

            rules.Add(R("<Condition/Operator>",
                        "Boolean operator in guard expression",
                        MappingType.ENCODED,
                        "Empty = TRUE, '-' = NOT",
                        "Phase 4: Guard conditions"));

            // ── Template-hardcoded interface & FB network ─────────────────────

            rules.Add(R("(none)",
                        "InterfaceList (INIT / REQ / CNF / INITO events + data vars)",
                        MappingType.HARDCODED,
                        $"Fixed interface defined inside {fbType} template — same for all instances",
                        "Template-defined, never modified per component"));

            rules.Add(R("(none)",
                        $"FBNetwork (internal FB wiring inside {fbType})",
                        MappingType.HARDCODED,
                        $"Pre-wired connections inside {fbType} template",
                        "Template-defined, never modified per component"));

            return rules;
        }

        // ─────────────────────────────────────────────────────────────────────
        // PRIVATE HELPERS
        // ─────────────────────────────────────────────────────────────────────

        private static MappingRule R(string vue, string iec, MappingType type,
                                     string rule, string notes) => new()
                                     {
                                         VueOneElement = vue,
                                         IEC61499Element = iec,
                                         Type = type,
                                         TransformationRule = rule,
                                         Notes = notes,
                                         Validated = true
                                     };

        private static string ResolveFbType(VueOneComponent c) => c.Type switch
        {
            "Actuator" when c.States.Count == 5 => "Five_State_Actuator_CAT",
            "Sensor" when c.States.Count == 2 => "Sensor_Bool_CAT",
            "Process" => "Process1_CAT",
            _ => $"UNKNOWN (Type={c.Type}, States={c.States.Count})"
        };

        private static (string iecElement, string rule) ResolveParam(VueOneComponent c)
        {
            if (c.Type == "Actuator")
                return ($"Parameter actuator_name := \"{c.Name}\"",
                        $"actuator_name injected into CAT instance");
            if (c.Type == "Process")
            {
                var stateList = string.Join(", ", c.States.OrderBy(s => s.StateNumber)
                                                          .Select(s => $"'{s.Name}'"));
                return ("Parameter Text := [state name list]",
                        $"Text := [{stateList}]");
            }
            return ("N/A", "No parameter injection for Sensor — SYMLINK handles I/O");
        }

        private static string Trunc(string s, int max) =>
            s.Length > max ? s[..max] + "…" : s;
    }
}