using System;
using CodeGen.Models;

namespace CodeGen.Mapping
{
    public class TemplateSelector
    {
        public FBTemplate? SelectTemplate(VueOneComponent component)
        {
            if (component == null)
                throw new ArgumentNullException(nameof(component));

            if (component.States == null)
                return null;

            if (string.Equals(component.Type, "Actuator", StringComparison.OrdinalIgnoreCase)
                && component.States.Count == 5)
            {
                return CreateTemplate("Five_State_Actuator_CAT.fbt", 5, "Actuator");
            }

            if (string.Equals(component.Type, "Sensor", StringComparison.OrdinalIgnoreCase)
                && component.States.Count == 2)
            {
                return CreateTemplate("Sensor_Bool_CAT.fbt", 2, "Sensor");
            }

            // Process components map to Process1_CAT via Phase 2 Inject System
            // They are NOT generated by Phase 1 Generate FB, but show the mapping in the UI
            if (string.Equals(component.Type, "Process", StringComparison.OrdinalIgnoreCase))
            {
                return CreateTemplate("Process1_CAT.fbt", component.States.Count, "Process");
            }

            return null;
        }

        private static FBTemplate CreateTemplate(string fileName, int stateCount, string componentType)
        {
            return new FBTemplate
            {
                TemplateName = fileName,
                TemplateFilePath = fileName,
                ExpectedStateCount = stateCount,
                ComponentType = componentType
            };
        }
    }
}