/*
 * Generated by VueOneMapper. The original code-behind only issued controller
 * commands, which a monitoring HMI must not do.
 */

using System;
using NxtControl.GuiFramework;

namespace HMI.Main.Symbols.Five_State_Actuator_CAT
{
	public partial class sSetup : NxtControl.GuiFramework.HMISymbol
	{
		public sSetup()
		{
			InitializeComponent();
		}
	}
}
