using System;
using System.Collections.Generic;
using CodeGen.Models;

namespace CodeGen.Translation
{
    /// <summary>
    /// Local-id mapping for components inside a station: sensors first (ids 0..N-1),
    /// then actuators (ids N..M-1). Used by ProcessRecipeArrayGenerator to derive
    /// Wait1Id / PusherID values that index into the runtime's state_table.
    /// </summary>
    public class StationComponentMap
    {
        public Dictionary<string, int> ComponentIdToLocalId { get; init; } = new(StringComparer.OrdinalIgnoreCase);
        public Dictionary<string, int> ComponentNameToLocalId { get; init; } = new(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Phase 1 leftover. The original class also emitted a Structured Text body that
    /// FbtRewriter spliced into ProcessRuntime_Generic_v1.fbt's initialize algorithm.
    /// That ST emission was deleted — recipe arrays now travel as syslay Parameter
    /// values per Process FB instance, generated by ProcessRecipeArrayGenerator.
    ///
    /// The only surviving member is BuildComponentMap, kept here because the new
    /// generator delegates to it (single source of truth for sensors-first ordering).
    /// </summary>
    public static class ProcessRecipeStGenerator
    {
        public static StationComponentMap BuildComponentMap(StationContents contents)
        {
            var map = new StationComponentMap();
            int next = 0;
            foreach (var s in contents.Sensors)
            {
                map.ComponentIdToLocalId[s.ComponentID] = next;
                map.ComponentNameToLocalId[s.Name] = next;
                next++;
            }
            foreach (var a in contents.Actuators)
            {
                map.ComponentIdToLocalId[a.ComponentID] = next;
                map.ComponentNameToLocalId[a.Name] = next;
                next++;
            }
            return map;
        }
    }
}
